package socialnetwork.utils;
import com.itextpdf.text.*;
import com.itextpdf.text.pdf.PdfWriter;
import socialnetwork.domain.Activity;

import java.io.FileOutputStream;
import java.util.ArrayList;
import java.util.Date;

public class ActivityPDF {
    private String user;
    private String title_doc;
    private ArrayList<Activity> activities;

    public ActivityPDF(String user, String title_doc, ArrayList<Activity> activities) {
        this.user = user;
        this.title_doc = title_doc;
        this.activities = activities;
    }

    public String getUser() {
        return user;
    }

    public void setUser(String user) {
        this.user = user;
    }

    public String getTitle_doc() {
        return title_doc;
    }

    public void setTitle_doc(String title_doc) {
        this.title_doc = title_doc;
    }

    public ArrayList<Activity> getActivities() {
        return activities;
    }

    public void setActivities(ArrayList<Activity> activities) {
        this.activities = activities;
    }

    private static String FILE = "ActivityPdf.pdf";
    private static Font catFont = new Font(Font.FontFamily.TIMES_ROMAN, 18,
            Font.BOLD);
    private static Font redFont = new Font(Font.FontFamily.TIMES_ROMAN, 12,
            Font.NORMAL, BaseColor.RED);
    private static Font subFont = new Font(Font.FontFamily.TIMES_ROMAN, 16,
            Font.BOLD);
    private static Font smallBold = new Font(Font.FontFamily.TIMES_ROMAN, 12,
            Font.BOLD);

    public void generatePDF() {

        try {
            Document document = new Document();

            PdfWriter.getInstance(document, new FileOutputStream(FILE));
            document.open();
            this.addMetaData(document);
            this.addTitlePage(document);
            this.addContent(document);
            document.close();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // iText allows to add metadata to the PDF which can be viewed in your Adobe
    // Reader
    // under File -> Properties
    private  void addMetaData(Document document) {
        document.addTitle(title_doc);
        document.addSubject("Using iText");
        document.addKeywords("Java, PDF, iText");
        document.addAuthor(user);
        document.addCreator(user);
    }

    private  void addTitlePage(Document document)
            throws DocumentException {
        Paragraph preface = new Paragraph();
        // We add one empty line
        addEmptyLine(preface, 1);
        // Lets write a big header
        preface.add(new Paragraph(title_doc, catFont));

        addEmptyLine(preface, 1);
        // Will create: Report generated by: _name, _date
        preface.add(new Paragraph(
                "Report generated by: " + user + ", " + new Date(), //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$
                smallBold));
        addEmptyLine(preface, 3);

        document.add(preface);

    }

    private  void addContent(Document document) throws DocumentException {


            for (Activity activity:activities) {
                document.add(new Paragraph(activity.toString(), subFont));
            }



    }


    private static void addEmptyLine(Paragraph paragraph, int number) {
        for (int i = 0; i < number; i++) {
            paragraph.add(new Paragraph(" "));
        }
    }
}

